name: Build and Test

on:
    push:
        branches:
            - main

jobs:
    build-and-release:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: setup jdk 8
              uses: actions/setup-java@v2
              with:
                  java-version: "8"
                  distribution: "temurin"
            - name: compile
              run: find . -name '*.java' | xargs javac
            - name: pack
              run: find . -name '*.class' | xargs jar cvmf META-INF/MANIFEST.MF TreeTemplatesInJava.jar
            - name: test
              run: java -jar TreeTemplatesInJava.jar -Local
